# mysql-password-updater-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-password-updater
  namespace: db-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PostSync
    secret.reloader.stakater.com/reload: "mysql-secret" # Restart when app secret changes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-password-updater
  template:
    metadata:
      labels:
        app: mysql-password-updater
    spec:
      restartPolicy: Always
      containers:
        - name: password-updater
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              set -e

              echo "========================================"
              echo "MySQL Password Updater"
              echo "Started at: $(date '+%Y-%m-%d %H:%M:%S')"
              echo "========================================"

              # Wait for MySQL to be ready
              echo ""
              echo "Step 1: Waiting for MySQL to be ready..."
              MAX_ATTEMPTS=60
              ATTEMPT=0

              while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
                if mysql -h ${DB_HOST} -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1" &>/dev/null 2>&1; then
                  echo "✓ MySQL is ready (attempt $((ATTEMPT+1)))"
                  break
                fi
                
                ATTEMPT=$((ATTEMPT+1))
                if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
                  echo "✗ MySQL did not become ready after ${MAX_ATTEMPTS} attempts"
                  exit 1
                fi
                
                echo "  Attempt ${ATTEMPT}/${MAX_ATTEMPTS}: Waiting for MySQL..."
                sleep 5
              done

              # Check if user already exists
              echo ""
              echo "Step 2: Checking current user status..."
              USER_EXISTS=$(mysql -h ${DB_HOST} -u root -p${MYSQL_ROOT_PASSWORD} -sN -e \
                "SELECT COUNT(*) FROM mysql.user WHERE user = '${MYSQL_APP_USER}'")

              if [ "$USER_EXISTS" -gt 0 ]; then
                echo "✓ User '${MYSQL_APP_USER}' exists - will update password"
                ACTION="Password Update"
              else
                echo "✓ User '${MYSQL_APP_USER}' does not exist - will create user"
                ACTION="User Creation & Setup"
              fi

              # Update/Create user with new password
              echo ""
              echo "Step 3: Executing ${ACTION}..."
              mysql -h ${DB_HOST} -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
              -- Create/Update user for any remote host (%)
              CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
              ALTER USER '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
              GRANT ALL PRIVILEGES ON ${DB_DATABASE}.* TO '${MYSQL_APP_USER}'@'%';

              # -- Create/Update user for localhost (Unix socket connections)
              # CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'localhost' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
              # ALTER USER '${MYSQL_APP_USER}'@'localhost' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
              # GRANT ALL PRIVILEGES ON ${DB_DATABASE}.* TO '${MYSQL_APP_USER}'@'localhost';

              -- Apply all changes
              FLUSH PRIVILEGES;

              -- Display configured users
              SELECT CONCAT('✓ ', user, '@', host, ' configured') AS Status
              FROM mysql.user 
              WHERE user = '${MYSQL_APP_USER}'
              ORDER BY host;
              EOF

              if [ $? -ne 0 ]; then
                echo "✗ Failed to configure user"
                exit 1
              fi

              # Verify new credentials work
              echo ""
              echo "Step 4: Verifying new credentials..."
              VERIFY_ATTEMPTS=0
              MAX_VERIFY_ATTEMPTS=10

              while [ $VERIFY_ATTEMPTS -lt $MAX_VERIFY_ATTEMPTS ]; do
                if mysql -h ${DB_HOST} -u ${MYSQL_APP_USER} -p${MYSQL_APP_PASSWORD} ${DB_DATABASE} -e "SELECT 1" &>/dev/null 2>&1; then
                  echo "✓ Credentials verified successfully"
                  break
                fi
                
                VERIFY_ATTEMPTS=$((VERIFY_ATTEMPTS+1))
                if [ $VERIFY_ATTEMPTS -eq $MAX_VERIFY_ATTEMPTS ]; then
                  echo "✗ Credential verification failed after ${MAX_VERIFY_ATTEMPTS} attempts"
                  exit 1
                fi
                
                echo "  Verification attempt ${VERIFY_ATTEMPTS}/${MAX_VERIFY_ATTEMPTS}..."
                sleep 2
              done

              echo ""
              echo "========================================"
              echo "✓ ${ACTION} completed successfully"
              echo "Completed at: $(date '+%Y-%m-%d %H:%M:%S')"
              echo "========================================"
              echo ""
              echo "Password update successful. Keeping container alive..."
              echo "This pod will restart when the secret changes."
              echo ""

              # Keep the container running and healthy
              # This allows Kubernetes to track the pod as healthy
              # and Reloader will restart it when secret changes
              while true; do
                # Health check every 60 seconds
                if mysql -h ${DB_HOST} -u ${MYSQL_APP_USER} -p${MYSQL_APP_PASSWORD} ${DB_DATABASE} -e "SELECT 1" &>/dev/null 2>&1; then
                  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Health check: ✓ Database connection OK"
                else
                  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Health check: ✗ Database connection failed"
                fi
                sleep 60
              done
          env:
            - name: DB_HOST
              value: "mysql-headless-service.db-namespace"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-secret
                  key: password
            - name: MYSQL_APP_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_APP_USER
            - name: MYSQL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_APP_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DATABASE_NAME
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          # Liveness probe to ensure container is healthy
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - mysql -h ${DB_HOST} -u ${MYSQL_APP_USER} -p${MYSQL_APP_PASSWORD} ${DB_DATABASE} -e "SELECT 1" &>/dev/null
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          # Readiness probe to know when password update is complete
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - mysql -h ${DB_HOST} -u ${MYSQL_APP_USER} -p${MYSQL_APP_PASSWORD} ${DB_DATABASE} -e "SELECT 1" &>/dev/null
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
