# cluster-external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: db-creds-ces
  # namespace: external-secrets   # <-- lives here
spec:
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore

    # refreshTime: "1m"
    refreshPolicy: Periodic
    refreshInterval: 1m

    target:
      name: db-creds-secret # name of the K8s Secret that will be created
      creationPolicy: Owner

  externalSecretData:
    - namespace: dev-db
      data:
        - secretKey: username
          remoteRef:
            key: dev-db # <-- exact path for dev
            property: username
        - secretKey: password
          remoteRef:
            key: dev-db
            property: password
    - namespace: prod-db
      data:
        - secretKey: username
          remoteRef:
            key: prod-db # <-- exact path for prod
            property: username
        - secretKey: password
          remoteRef:
            key: prod-db
            property: password

  # namespaceSelector:
  #   matchLabels: {} # empty = all namespaces listed below
  namespaces:
    - dev-db
    - prod-db
