apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://host.docker.internal:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-secret"
          namespace: "test-me"
          key: "token"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-token
# data:
#   token: cm9vdA== # "root"
