apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  provider:
    # For AWS Secret Manager
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
          region: ap-south-1
    # For HASICORPT VAULT Configuration
    # vault:
    #   server: "http://host.docker.internal:8200"
    #   path: "secret"
    #   version: "v2"
    #   auth:
    #     tokenSecretRef:
    #       name: "vault-secret"
    #       namespace: "test-me"
    #       key: "token"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-token
# data:
#   token: cm9vdA== # "root"
