apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: db-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook: preSync
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "-1"
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: "dev-db"
        property: "password"
