apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: db-namespace
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  # volumeName: mysql-pv
