apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: db-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Apply first
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ""
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  # volumeName: mysql-pv
